### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/soltar#1]
- [ ] Demo on gh-pages
- [ ] Add Command-line utility
- [ ] Write tests & set up coverage info
- [ ] Minify soltar-bundle.js
- [x] browser compatibility
- [x] Inform of currently un-patched bug in StructDeclaration in solidity-parser and in IsStatement
